spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
